---
- hosts: frontends
  remote_user: ubuntu

  tasks:
    - name: ensure node is installed
      shell: dpkg -s nodejs
      register: result
      ignore_errors: True

    - name: add nodejs repo
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_11.x | bash -
      when: result.rc == 1

    - name: install nodejs
      apt:
        name: nodejs
        state: present	
      become: yes

    - name: install pm2
      npm:
        name: pm2
        version: '3.4.0'
        global: yes
      notify: start pm2
      become: yes

    - name: clone project
      git:
        repo: git@github.com:limboaz/StackTraceException.git
        dest: ~/StackTraceException
        accept_hostkey: yes
        update: yes
      notify: restart project

    - name: install npm modules
      shell: cd ~/StackTraceException && npm install

  handlers:
    - name: start pm2
      shell: pm2 start && pm2 install pm2-logrotate && pm2 set pm2-logrotate:compress true

    - name: restart project
      shell: cd ~/StackTraceException && pm2 flush && pm2 restart www
...
